title: Iran-e Bidar
description: A multilingual Jekyll site
baseurl: ""
url: "http://localhost:4000"

# Build settings
markdown: kramdown
highlighter: rouge

# Collections
collections:
  pages:
    output: true
    permalink: /:name/

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"