title: Iran-e Bidar
description: A multilingual Jekyll site
baseurl: ""
url: "http://localhost:4000"

# Multilingual configuration
languages: ["en", "de"]
default_lang: "en"
exclude_from_localizations: ["javascript", "images", "css"]

plugins:
  - jekyll-multiple-languages-plugin

# Build settings
markdown: kramdown
highlighter: rouge

# Collections
collections:
  pages:
    output: true
    permalink: /:name/

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"